// default package
// Generated Apr 23, 2014 9:20:49 AM by Hibernate Tools 3.4.0.CR1
package com.qlydb.action;

import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team implements java.io.Serializable {

    private String nameTeam;
    private int diem;
    private int hieuso;
    private int idteam;
    private Set results = new HashSet(0);

    public Team() {
    }

    public int getDiem() {
        return diem;
    }

    public void setDiem(int diem) {
        this.diem = diem;
    }

    public int getHieuso() {
        return hieuso;
    }

    public void setHieuso(int hieuso) {
        this.hieuso = hieuso;
    }

    public int getIdteam() {
        return idteam;
    }

    public void setIdteam(int idteam) {
        this.idteam = idteam;
    }

    public String getNameTeam() {
        return this.nameTeam;
    }

    public void setNameTeam(String nameTeam) {
        this.nameTeam = nameTeam;
    }

    @SuppressWarnings("rawtypes")
    public Set getResults() {
        return this.results;
    }

    @SuppressWarnings("rawtypes")
    public void setResults(Set results) {
        this.results = results;
    }

}
